services:
  postgres:
    image: postgres:16
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-tempo}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-tempo}
      POSTGRES_DB: ${POSTGRES_DB:-tempo}
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-tempo}"]
      interval: 10s
      timeout: 5s
      retries: 5
    # No ports: queda solo interno en la red docker

  api:
    build: ./apps/api
    restart: unless-stopped
    environment:
      DATABASE_URL: postgresql+psycopg://${POSTGRES_USER:-tempo}:${POSTGRES_PASSWORD:-tempo}@postgres:5432/${POSTGRES_DB:-tempo}
      API_KEY: ${API_KEY:-changeme}
      BASE_URL: ${BASE_URL:-https://carlosjg.space}
      # En prod evita "*" para no abrirte de más
      CORS_ORIGINS: ${CORS_ORIGINS:-https://carlosjg.space,https://www.carlosjg.space}
      MEDIA_ROOT: /data/media
    volumes:
      - ./data/media:/data/media
      - ./apps/api/.env:/app/.env:ro
    depends_on:
      postgres:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "python -c \"import urllib.request; urllib.request.urlopen('http://localhost:8000/api/health')\""]
      interval: 10s
      timeout: 5s
      retries: 5
    expose:
      - "8000"

  web:
    build: ./apps/web
    restart: unless-stopped
    environment:
      # Como Caddy está en frente, usar /api es perfecto.
      VITE_API_BASE: ${VITE_API_BASE:-/api}
    depends_on:
      api:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "wget -qO- http://localhost:4173 >/dev/null 2>&1"]
      interval: 10s
      timeout: 5s
      retries: 5
    expose:
      - "4173"

  caddy:
    image: caddy:2
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    environment:
      # Tu Caddyfile usa {$DOMAIN:localhost}
      DOMAIN: ${DOMAIN:-carlosjg.space}
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - caddy_data:/data
      - caddy_config:/config
    depends_on:
      api:
        condition: service_healthy
      web:
        condition: service_healthy

volumes:
  db_data:
  caddy_data:
  caddy_config:
